name: Create new release

permissions:
  contents: write
  packages: write

on:
  push:
    paths:
      - 'JavaWebScraper/app/pom.xml'
      - 'JavaWebScraper/cli/pom.xml'
      - 'JavaWebScraper/common/pom.xml'
      - 'JavaWebScraper/pom.xml'

jobs:
  build:
    name: Build project on Windows
    runs-on: windows-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 24 with JavaFX
        uses: graalvm/setup-graalvm@v1
        with:
          distribution: 'liberica'
          java-version: '24'
          java-package: 'jdk+fx'

      - name: Build project
        run: |
          cd JavaWebScraper
          mvn -v
          chmod +x builder.sh
          ./builder.sh

      - name: Get shared app version from Maven
        id: get_version
        run: |
          cd JavaWebScraper/app
          VERSION=$(mvn help:evaluate -Dexpression=project.version.shared -q -DforceStdout)
          echo "Shared app version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Upload JAR artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jars
          path: |
            JavaWebScraper/plugins/gif/target/*.jar
            JavaWebScraper/plugins/history/target/*.jar
            JavaWebScraper/app/target/*.jar
            JavaWebScraper/cli/target/*.jar
            JavaWebScraper/common/target/*.jar

  deploy:
    name: Deploy and release on Ubuntu
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download JAR artifacts
        uses: actions/download-artifact@v4
        with:
          name: jars
          path: jars

      - name: Deploy project with SSH
        uses: easingthemes/ssh-deploy@v2.1.4
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          SOURCE: "./jars/"
          TARGET: "~/java"

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.build.outputs.version }}
          release_name: Release v${{ needs.build.outputs.version }}
          body: |
            Plugins for the JavaWebScraper project:
            - History plugin
            - Gif plugin
          files: |
            jars/gif-${{ needs.build.outputs.version }}.jar
            jars/history-${{ needs.build.outputs.version }}.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Execute remote release script via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            chmod +x java/JavaWebScraper/create-release.sh
            ./java/JavaWebScraper/create-release.sh \
              ${{ secrets.PATHTOJAVA }} \
              v${{ needs.build.outputs.version }} \
              ${{ needs.build.outputs.version }} \
              ${{ secrets.URL }}app-${{ needs.build.outputs.version }}.jar app-${{ needs.build.outputs.version }}.jar \
              ${{ secrets.URL }}cli-${{ needs.build.outputs.version }}.jar cli-${{ needs.build.outputs.version }}.jar \
              ${{ secrets.URL }}common-${{ needs.build.outputs.version }}.jar common-${{ needs.build.outputs.version }}.jar
