name: Deploy on VPS

permissions:
  contents: write
  packages: write
on:
  push:
    branches:
    - main
    - troc
  pull_request:
    branches:
    - main

jobs:
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['18.x', '20.x']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node_version }}

    - name: npm install
      run: |
        cd API
        npm install
        cd ../Next_Door_Buddy
        npm install
    - name: Deploy to VPS
      env:
        SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.HOST }}
        REMOTE_USER: ${{ secrets.USERNAME }}
        SOURCE: "/"
        TARGET: "~"
      run: |
         echo "$SSH_PRIVATE_KEY" > private_key.pem # Write the private key to a file
         chmod 600 private_key.pem # Set the appropriate permissions for the key file
        
         # Establish an SSH connection and execute commands on the remote server
         ssh -o StrictHostKeyChecking=no -i private_key.pem "$REMOTE_USER"@"$REMOTE_HOST" <<EOF
          cd ~/Projet_Annuel_3AL
          cd API
          docker compose up -d 
          cd ../Next_Door_Buddy 
          npm run dev &
          cd ../API
          npm run dev &
          EOF
          rm -f private_key.pem
    permissions:
      contents: read
      actions: write
      id-token: write