name: Deploy on VPS

permissions:
  contents: write
  packages: write
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['18.x', '20.x']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node_version }}

    - name: npm install, build and test
      run: |
        cd API
        npm install
        npm run build --if-present
        npm test
        cd ../Next_Door_Buddy
        npm install
        npm run build --if-present
        npm test
    - name: Deploy to VPS
      uses: easingthemes/ssh-deploy@v2.1.4
      env:
        SSH_PRIVATE_KEY: ${{ secrets.VPS_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.VPS_HOST }}
        REMOTE_USER: ${{ secrets.VPS_USERNAME }}
        SOURCE: "/"
        TARGET: "~"
    - name: Execute remote release script via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_PRIVATE_KEY }}
        port: 22
        script: |
          cd ~/Projet_Annuel_3AL
          cd API
          docker compose up -d 
          cd ../Next_Door_Buddy 
          npm run dev &
          cd ../API
          npm run dev &
