name: Deploy on VPS

permissions:
  contents: write
  packages: write
on:
  push:
    branches:
    - main
    - troc
  pull_request:
    branches:
    - main

jobs:
  test:
    name: Test on node ubuntu-latest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: npm install
      run: |
        cd API
        npm install
        cd ../Next_Door_Buddy
        npm install
    - name: Deploy to VPS
      env:
        SSH_PRIVATE_KEY: ${{ secrets.VPS_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.VPS_HOST }}
        REMOTE_USER: ${{ secrets.VPS_USERNAME }}
        SOURCE: "/"
        TARGET: "~"
      run: |
         echo "$SSH_PRIVATE_KEY" > private_key.pem # Write the private key to a file
         chmod 600 private_key.pem # Set the appropriate permissions for the key file
        
         # Establish an SSH connection and execute commands on the remote server
         ssh -o StrictHostKeyChecking=no -i private_key.pem "$REMOTE_USER"@"$REMOTE_HOST" << EOF
            # Navigate to the project directory and pull the latest changes
          cd ~
          git clone git@github.com:M4THIA5/Projet_Annuel_3AL.git
          cd Projet_Annuel_3AL
          cd API
          docker compose up -d 
          cd ../Next_Door_Buddy 
          npm run dev &
          cd ../API
          npm run dev &
          EOF
          rm -f private_key.pem
    permissions:
      contents: read
      actions: write
      id-token: write